FROM alpine:latest

RUN chmod -R 777 /usr/bin

COPY ./minio-linux-riscv64 /usr/bin/minio

COPY dockerscripts/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

CMD ["minio"]
